<?php
/**
 * @var MercadoPago\MercadoEnvios\Block\Adminhtml\System\Config\Fieldset\Mapping $block
 */
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
$productCode = $block->_getAttributes();
$sizeUnit = ['cm', 'mt'];
$weightUnit = ['kg', 'gr'];
$meCode = ['length','width','height', 'weight'];
$meLabel = $block->_getMeLabel();
$prevValues = [];
$unit = $sizeUnit;

$prevValues = $block->_getStoredMappingValues();

?>

<div class="grid" id="grid<?= /* @noEscape */ $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border admin__control-table">
        <tr class="headings" id="headings<?= /* @noEscape */ $_htmlId ?>">
            <th><?= /* @escapeNotVerified */__('MercadoEnvios')?></th>
            <th><?= /* @escapeNotVerified */__('Product Attribute')?></th>
            <th><?= /* @escapeNotVerified */__('Product Attribute Unit')?></th>
        </tr>
        <?php foreach ($meCode as $key => $meOption) :?>
            <tr id="<?= /* @noEscape */ $meOption ?>">
                    <td>
                        <label><?= $block->escapeHtml($meLabel[$key]) ?>:</label>
                    </td>
                    <td>
                        <?php
                        $selectName = 'groups[mercadoenvios][fields][attributesmapping][value][' . $meOption
                            . '][attribute_code]';
                        ?>
                        <select name="<?= /* @noEscape */ $selectName ?>">
                            <?php foreach ($productCode as $option) : ?>
                                <option value="<?= $block->escapeQuote($option->getAttributeCode()) ?>"
                                    <?php $optinSelected = isset($prevValues[$meOption]['attribute_code'])
                                        && $prevValues[$meOption]['attribute_code'] == $option->getAttributeCode(); ?>
                                    <?= /* @noEscape */ $optinSelected ? "selected='selected'" : "" ?>>
                                    <?= $block->escapeHtml($option->getFrontendLabel()) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <?php
                    if ($meOption == 'weight') {
                        $unit = $weightUnit;
                    }
                    ?>
                    <td>
                        <?php
                        $selectName = 'groups[mercadoenvios][fields][attributesmapping][value][' . $meOption
                            . '][unit]';
                        ?>
                        <select name="<?= /* @noEscape */ $selectName ?>">
                            <?php foreach ($unit as $_u) :?>
                                <option value="<?= /* @noEscape */ $_u ?>"
                                        <?= /* @noEscape */ (isset($prevValues[$meOption]['unit'])
                                            && $prevValues[$meOption]['unit'] == $_u) ? "selected='selected'" : '' ?>>
                                    <?= /* @noEscape */ $_u ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
