<?php
/**
 * @var MercadoPago\Core\Block\Custom\Success $block
 */
    $order = $this->getOrder();
    $total = $this->getTotal();
    $payment = $this->getPayment();
    
    //monta link para o pedido
    $link_to_order = '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">'
        . $block->escapeHtml($order->getIncrementId()) . '</a>';
    $successMsg = 'Your order %1 has been successfully generated.';
    
    $payment_method = $this->getPaymentMethod();
    $info_payment = $this->getInfoPayment();
?>

<div id="box-mercadopago">

    <?php if (!isset($info_payment['status']['value'])) : ?>
        <h2 class="mercadopago-title"><?= /* @escapeNotVerified */ __('Thank you for your purchase!'); ?></h2>
        <p><?= /* @escapeNotVerified */ __($successMsg, $link_to_order); ?></p>
    <?php else : ?>
        <?php
            $message_status = $this->getMessageByStatus(
                $info_payment['status']['value'],
                $info_payment['status_detail']['value'],
                (isset($info_payment['payment_method']['value'])) ? $info_payment['payment_method']['value'] : '',
                (isset($info_payment['installment']['value'])) ? $info_payment['installment']['value'] : '',
                $this->getTotal()
            );
        ?>
        <h2 class="mercadopago-title"><?= $block->escapeHtml($message_status['title']); ?></h2>

        <p><?= $block->escapeHtml($message_status['message']); ?></p>

        <p><?= /* @escapeNotVerified */ __($successMsg, $link_to_order); ?></p>

        <h3 class="mercadopago-title-info-payment"><?= /* @escapeNotVerified */ __('Payment information'); ?></h3>

        <?php foreach ($info_payment as $info) : ?>
            <p><?= /* @escapeNotVerified */ __($info['text']); ?></p>
        <?php endforeach; ?>
            
    <?php endif; ?>
</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png" /> 
</div>


<div class="primary button-success">
    <a class="action primary continue" href="<?= $block->escapeUrl($block->getUrl()) ?>">
        <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
    </a>
</div>

