<?php
/**
 * @var MercadoPago\Core\Block\Standard\Success $block
 */

$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();

$successMsg = 'Your order %1 has been successfully generated.';
$linkToOrder = '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">'
    . $block->escapeHtml($order->getIncrementId()) . '</a>';

$paymenMethod = $this->getPaymentMethod();
$infoPayment = $this->getInfoPayment();
?>

<div id="box-mercadopago">

    <?php if (!isset($infoPayment['status']['value'])) : ?>
        <h2 class="mercadopago-title">
            <?= /* @escapeNotVerified */ __('Thank you for your purchase!'); ?>
        </h2>
        <p><?= /* @escapeNotVerified */ __($successMsg, $linkToOrder); ?></p>
    <?php else : ?>
        <?php
        $message_status = $this->getMessageByStatus(
            (isset($infoPayment['status']['value'])?$infoPayment['status']['value']:''),
            (isset($infoPayment['status_detail']['value']))?$infoPayment['status_detail']['value']:'',
            (isset($infoPayment['payment_method']['value']))?$infoPayment['payment_method']['value']:'',
            (isset($infoPayment['installment']['value']))?$infoPayment['installment']['value']:'',
            $this->getTotal()
        );
        ?>
        <h2 class="mercadopago-title"><?= $block->escapeHtml($message_status['title']); ?></h2>

        <p><?= $block->escapeHtml($message_status['message']); ?></p>

        <p><?= /* @escapeNotVerified */ __($successMsg, $linkToOrder); ?></p>

        <h3 class="mercadopago-title-info-payment"><?= /* @escapeNotVerified */ __('Payment information'); ?></h3>

        <?php foreach ($infoPayment as $info) : ?>
            <p><?= /* @escapeNotVerified */ __($info['text']); ?></p>
        <?php endforeach; ?>

    <?php endif ?>

</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png"/>
</div>


<div class="primary button-success">
    <a class="action primary continue" href="<?= $block->escapeUrl($block->getUrl()) ?>">
        <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
    </a>
</div>
