<?php
/**
 * @var MercadoPago\Core\Block\CustomTicket\Success $block
 */
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();

$link_to_order = __(
    'Your order %1 has been successfully generated.',
    '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>'
);

$payment_method = $this->getPaymentMethod();
$info_payment = $this->getInfoPayment();
?>

<div id="box-mercadopago">

    <?php if ($payment_method == 'mercadopago_customticket') : ?>
        <h2 class="mercadopago-title"><?= /* @escapeNotVerified */ __('Thank you for your purchase!'); ?></h2>

        <p>
            <?php /* @escapeNotVerified */ echo $link_to_order; ?>
        </p>

        <p>
            <?= 'Generate the ticket and pay it wherever you want.'; ?>
        </p><p>
            <?= /* @escapeNotVerified */ __('Will be approved within 2 business days.'); ?>
        </p>
        <a href="<?= $block->escapeUrl(urldecode($payment->getAdditionalInformation('activation_uri'))); ?>"
           target="_blank" id="btn-boleto-mercadopago">
            <?= /* @escapeNotVerified */ __('Generate Ticket'); ?>
        </a>

    <?php endif; ?>

</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png"/>
</div>

<div class="primary button-success">
    <a class="action primary continue" href="<?= $block->escapeUrl($block->getUrl()) ?>">
        <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
    </a>
</div>
